### ISSUE TITLE
Results are different compared to waifu2x.udp.jp with same image and settings?

### ISSUE THREAD

**Issue by NintendoManiac64** [DeadSix27/waifu2x-converter-cpp#205]
I can't help but notice that the results I'm getting from waifu2x-converter-cpp (albeit via snowshell) are different than the results I'm getting with waifu2x.udp.jp.

One thing in particular I've also noticed is that snowshell v1.9 and v2.1 (which were compiled 2 years apart) give identical results with the same settings (that is when using GPU for both), but waifu2x.udp.jp updated their algorithm in late 2018, an update that doesn't seem to be present in waifu2x-converter-cpp.

Does this mean that waifu2x-converter-cpp uses a different implementation of the waifu2x algorithm than waifu2x.udp.jp does, or has waifu2x-converter-cpp simply not had its waifu2x algorithm updated to a more recent version?

**Comment by YukihoAA** [comment]
It is difference with model file. also, waifu2x-converter-cpp only supports vgg_7 when waifu2x.udp.jp supports cunet model. it is different because model file is not same. you can think model file is script to run waifu2x algorithm, since script is different, it should be get different result. so it is expected. we want to implement upconv7 at least. but it is hard to do it. I implemented by caffemodel support. but it is not what waifu2x-converter-cpp used to work. it is more like waifu2x-caffe and in opencv caffemode is not efficiency so i will not merge that branch.

1. It SHOULD be different.
2. waifu2x-converter-cpp need improvement to support upconv7 and cunet models. (new models)
3. you maybe can consider to use waifu2x-caffe if you want closest result with waifu2x.udp.jp
