### ISSUE TITLE
Level 1 and 2 denoise leave artifacts

### ISSUE THREAD

**Issue by Arkbird1000** [DeadSix27/waifu2x-converter-cpp#51]
I've recently noticed that Levels 1 and 2 for denoise leave artifacts behind in some cases, while Level 3 seems to clear them up just fine (though with the added detail loss). [Here](https://imgur.com/a/JCvX0) is a link to an example album of a portion of the original image and then the three denoise settings outputs.

I've tested this using your latest release on my main machine (R7 1700, RX 480 8GB, Adrenalin 17.12.2, Windows 8.1) and on my laptop (i7-7560U, Windows 10). I also gave caffe a shot on my main machine, and it has the same issues (though one combination of settings output similar to Level 3 above, but not quite as clean). An older version of converter-cpp (1130 from tanakamura) does not display these problems, nor does the online version.

Oh, and if it makes a difference, I am using a slightly modified version of max20091's CMD GUI. Nothing special, just added some options for my sake.

**Comment by YukihoAA** [comment]
Hi, @Arkbird1000 
I checked 3 converter's noise reduction in level 1, I think they have no big difference. -> [Link](https://imgur.com/a/e4gRt)

Since waifu2x is based on CuDNN technology, some images cannot be clearly Denise. (it's based on statistic)
Also, Latest model file works better on most of images, but some images may old one is better.
Online version may have updated model file because It continuously trained by online based on CuDNN.
But since we don't have much resources to train them, We cannot get better model file. 

Again, DeadSix27's model file is latest model file we can get.

**Comment by Arkbird1000** [comment]
I'd been wondering if the models being used were part of it. Admittedly, I don't have a complete grasp of how waifu2x works beyond some basic concepts, so I'm not surprised. Well, I guess it's not really an issue then. I'll just close this and keep different waifu2x versions handy.

Thank you very much @YukihoAA!
